### ISSUE TITLE
ES6 auto conversions to the ejs public directory.

### ISSUE THREAD

**Issue by afaur** [afaur/vibrant#2]
This is the line in the compiler that converts the user's ES6 files to js:
https://github.com/afaur/vibrant/blob/master/source/compiler/js/babel.d#L52

It is called here:
https://github.com/afaur/vibrant/blob/master/source/compiler/base_compiler.d#L16

Since babel supports a glob path of files it would be cool to auto convert any .ejs files located in the project under assets/ES6/_.ejs to become js files in public/ejs/_.js

**Comment by bayleedev** [comment]
Why are you trying to convert them? I don't see any `ejs` files in this project.

**Comment by afaur** [comment]
https://github.com/afaur/vibrant/blob/master/assets/ES6/index-2.ejs

It's just an example file and it's being manually converted now by having to add an instruction for it here:
https://github.com/afaur/vibrant/blob/master/source/compiler/base_compiler.d#L16

So the implementation would make that line in the base_compiler become a glob or let you specify to convert all ejs files located in the directory.

**Comment by bayleedev** [comment]
Oh, I see. You're making a framework.

Like other frameworks, maybe this should be middleware somehow? Like a plugin you explicitly add. There should be hooks or events or something.

**Comment by afaur** [comment]
Good idea, maybe I will close this and come up with a better solution to open an issue over.
